In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
warnings.filterwarnings('ignore')
%matplotlib inline

In [6]:
from sklearn.datasets import fetch_20newsgroups

news_data = fetch_20newsgroups(subset='all', random_state=156)

In [12]:
train_news = fetch_20newsgroups(subset='train', remove=('headers','footers','quotes'),
                               random_state=156)
x_train = train_news.data
y_train = train_news.target

<class 'list'> 7532


In [11]:
test_news = fetch_20newsgroups(subset='test', remove=('headers','footers','quotes'),
                               random_state=156)
x_test = test_news.data
y_test = test_news.target

<class 'list'> 7532


In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(x_train)
x_train_tfidf_vect = tfidf_vect.transform(x_train)
x_test_tfidf_vect = tfidf_vect.transform(x_test)

lr_clf = LogisticRegression()
lr_clf.fit(x_train_tfidf_vect, y_train)
pred = lr_clf.predict(x_test_tfidf_vect)

In [32]:
tfidf_vect =TfidfVectorizer(stop_words='english', ngram_range=(1,2), max_df=300)
tfidf_vect.fit(x_train)
x_train_tfidf_vect = tfidf_vect.transform(x_train)
x_test_tfidf_vect = tfidf_vect.transform(x_test)

In [33]:
lr_clf = LogisticRegression()
lr_clf.fit(x_train_tfidf_vect, y_train)
pred = lr_clf.predict(x_test_tfidf_vect)

In [34]:
accuracy_score(y_test, pred)

0.6922464152947424

In [69]:
pred[:5]

array([ 3, 11,  1,  7,  8])

## DT

In [36]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train_tfidf_vect, y_train)
pred_dtc = dtc.predict(x_test_tfidf_vect)

In [37]:
accuracy_score(y_test, pred_dtc)

0.485926712692512

In [72]:
pred_dtc[:5]

array([3, 8, 1, 8, 8])

 ## SVM

In [38]:
svc = SVC()
svc.fit(x_train_tfidf_vect, y_train)
pred_svc = svc.predict(x_test_tfidf_vect)

In [39]:
accuracy_score(y_test, pred_svc)

0.6783058948486458

In [73]:
pred_svc[:5]

array([3, 7, 1, 7, 8])

## RF

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
rf = RandomForestClassifier()
rf.fit(x_train_tfidf_vect, y_train)
pred_rf = rf.predict(x_test_tfidf_vect)

In [58]:
accuracy_score(y_test, pred_rf)

0.6307753584705258

In [74]:
pred_rf[:5]

array([3, 8, 1, 7, 8])

## VC

In [50]:
from sklearn.ensemble import VotingClassifier

In [61]:
vc = RandomForestClassifier()
vc.fit(x_train_tfidf_vect, y_train)
pred_vc = vc.predict(x_test_tfidf_vect)

In [62]:
accuracy_score(y_test, pred_vc)

0.6326340945300053

In [75]:
pred_vc[:5]

array([3, 8, 1, 7, 8])